package util;

import java.io.Serializable;

public class Message implements Serializable {

	/**
	 * Autogenerated.
	 */
	private static final long serialVersionUID = 8502435830459870335L;
	private String host;
	private int port;
	private MessageType type;
	private String meth;
	private String name;
	private Object[] args;

	private Message(String host, int port, MessageType type, String meth,
			String name, Object[] args) {
		super();
		this.host = host;
		this.port = port;
		this.type = type;
		this.meth = meth;
		this.name = name;
		this.args = args;
	}

	public static Message newRequest(String host, int port, String meth,
			String name, Object[] args) {
		return new Message(host, port, MessageType.REQUEST, meth, name, args);
	}

	public static Message newReply(String host, int port, String meth,
			String name, Object[] args) {
		return new Message(host, port, MessageType.REPLY, meth, name, args);
	}

	public String getHost() {
		return host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	public int getPort() {
		return port;
	}

	public void setPort(int port) {
		this.port = port;
	}

	public String getMeth() {
		return meth;
	}

	public void setMeth(String meth) {
		this.meth = meth;
	}

	public MessageType getType() {
		return this.type;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Object[] getArgs() {
		return args;
	}

	public void setArgs(Object[] args) {
		this.args = args;
	}

}
