package worker.processmigration;

/**
 * Abstract base class for a migratable process.
 * 
 * @author Michael
 *
 */
public abstract class AbstractMigratableProcess implements MigratableProcess {

	private int processID;
	
	/**
	 * Autogenerated.
	 */
	private static final long serialVersionUID = -6377473230297741870L;

	@Override
	public abstract void run();
	
	public int getProcessID() {
		return processID;
	}
	
	
}
