package worker.processmigration;

/**
 * Abstract base class for a migratable process.
 * 
 * @author Michael
 *
 */
public abstract class AbstractMigratableProcess implements MigratableProcess {

	private int processID;
	private int clientID;
	
	public int getClientID() {
		return clientID;
	}

	public void setClientID(int clientID) {
		this.clientID = clientID;
	}

	/**
	 * Autogenerated.
	 */
	private static final long serialVersionUID = -6377473230297741870L;

	@Override
	public abstract void run();
	
	@Override
	public int getProcessID() {
		return processID;
	}
	
	@Override
	public void setProcessID(int id) {
		processID = id;
	}
	
	
}
