package worker.processmigration;

/**
 * Abstract base class for a migratable process.
 * 
 * @author Michael
 *
 */
public abstract class AbstractMigratableProcess implements MigratableProcess {

	/**
	 * Autogenerated.
	 */
	private static final long serialVersionUID = -6377473230297741870L;

	@Override
	public abstract void run();
	
}
